name: lgtm

services:
  otel-collector:
    image: otel/opentelemetry-collector:0.80.0
    restart: unless-stopped
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
    - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      tempo:
        condition: service_healthy
      loki:
        condition: service_healthy
      mimir-1:
        condition: service_healthy
      mimir-2:
        condition: service_healthy
      mimir-3:
        condition: service_healthy
    ports:
    - 4317:4317 # For gRPC
    - 4318:4318 # For HTTP

  mimir-1:
    image: grafana/mimir:2.15.0
    command: ["-config.file=/etc/mimir.yaml"]
    hostname: mimir-1
    healthcheck:
      test: wget --quiet --tries=1 --output-document=- http://localhost:9009/ready
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      create_bucket:
        condition: service_completed_successfully
    volumes:
      - ./config/mimir.yaml:/etc/mimir.yaml
      - ./config/alertmanager-fallback-config.yaml:/etc/alertmanager-fallback-config.yaml
      - ./volumes/mimir-1-data:/data

  mimir-2:
    image: grafana/mimir:2.15.0
    command: ["-config.file=/etc/mimir.yaml"]
    hostname: mimir-2
    healthcheck:
      test: wget --quiet --tries=1 --output-document=- http://localhost:9009/ready
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      create_bucket:
        condition: service_completed_successfully
    volumes:
      - ./config/mimir.yaml:/etc/mimir.yaml
      - ./config/alertmanager-fallback-config.yaml:/etc/alertmanager-fallback-config.yaml
      - ./volumes/mimir-2-data:/data

  mimir-3:
    image: grafana/mimir:2.15.0
    command: ["-config.file=/etc/mimir.yaml"]
    hostname: mimir-3
    healthcheck:
      test: wget --quiet --tries=1 --output-document=- http://localhost:9009/ready
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      create_bucket:
        condition: service_completed_successfully
    volumes:
      - ./config/mimir.yaml:/etc/mimir.yaml
      - ./config/alertmanager-fallback-config.yaml:/etc/alertmanager-fallback-config.yaml
      - ./volumes/mimir-3-data:/data

  loki:
    image: grafana/loki:3.3.2
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
      test: wget --quiet --tries=1 --output-document=- http://localhost:3100/ready
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      create_bucket:
        condition: service_completed_successfully
    environment:
    - LOKI_PORT=3100
    volumes:
    - ./config/loki-config.yaml:/etc/loki/local-config.yaml
    - ./volumes/loki-data:/loki
    ports:
    - 3100:3100
  
  minio:
    image: minio/minio
    restart: unless-stopped
    env_file: .env
    volumes:
    - ./volumes/minio-data:/data
    ports:
    - 9000:9000
    - 9001:9001
    command: server /data --console-address :9001

  create_bucket:
    image: minio/mc
    depends_on:
    - minio
    entrypoint:
    - /bin/sh
    - -c
    - |
      until mc alias set myminio http://minio:9000 "${MINIO_ROOT_USER}" "${MINIO_ROOT_PASSWORD}"; do
        echo "Waiting for MinIO..."
        sleep 2
      done;
      mc mb --ignore-existing myminio/loki;
      mc anonymous set public myminio/loki;
      mc mb --ignore-existing myminio/tempo;
      mc anonymous set public myminio/tempo;
      mc mb --ignore-existing myminio/mimir;
      mc anonymous set public myminio/mimir;
      exit 0;
    env_file: .env
    volumes:
    - ./volumes/minio-data:/data

  grafana:
    image: grafana/grafana-oss:11.4.0-ubuntu
    restart: unless-stopped
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=testing321
    ports:
    - 3000:3000
    depends_on:
    - loki
    - tempo
    - mimir-1
    - mimir-2
    - mimir-3
    volumes:
    - ./config/grafana-provisioning:/etc/grafana/provisioning
    - ./volumes/grafana-data:/var/lib/grafana
    - ./volumes/grafana-logs:/var/log/grafana

  tempo:
    image: grafana/tempo:2.7.0
    restart: unless-stopped
    command: [ "-config.file=/etc/tempo.yaml" ]
    healthcheck:
      test: wget --quiet --tries=1 --output-document=- http://localhost:3200/ready
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      create_bucket:
        condition: service_completed_successfully
    volumes:
    - ./config/tempo.yaml:/etc/tempo.yaml
    - ./volumes/tempo-data:/var/tempo
    post_start:
    - command: chown -R 10001:10001 /var/tempo
      user: root
    ports:
    - 3200 # tempo
    - 4317 # otlp grpc
    - 4318 # otlp http
