auth_enabled: false

server:
  http_listen_port: 3100

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  ring:
    kvstore:
      store: inmemory
  replication_factor: 1

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

limits_config:
  allow_structured_metadata: true
  metric_aggregation_enabled: true
  # Assume month 31 days.
  #   - Keep Global Retention for a maximum of One Month.
  #   - Critical Services for Up to 1 year. "Production Workaround".
  #   - Dev Environments for 14 days.
  retention_period: 744h
  # retention_stream:
  # - selector: '{namespace="dev"}'
  #   priority: 1
  #   period: 24h

schema_config:
  configs:
  - from: 2024-04-01
    object_store: s3
    store: tsdb
    schema: v13
    index:
      period: 24h
      prefix: index_

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    resync_interval: 5s
  aws:
    s3: http://x62hAFEb4wkRNRaR:IF1r6ZtELYWbKmBFOamMpj0XjK2W96sW@minio.:9000/loki
    s3forcepathstyle: true

compactor:
  working_directory: /loki/retention
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: s3

query_scheduler:
  # the TSDB index dispatches many more, but each individually smaller, requests. 
  # We increase the pending request queue sizes to compensate.
  max_outstanding_requests_per_tenant: 32768

querier:
  # Each `querier` component process runs a number of parallel workers to process queries simultaneously.
  # You may want to adjust this up or down depending on your resource usage
  # (more available cpu and memory can tolerate higher values and vice versa),
  # but we find the most success running at around `16` with tsdb
  max_concurrent: 16

# pattern_ingester:
#   enabled: true
#   metric_aggregation:
#     enabled: true
#     loki_address: localhost:3100

# ruler:
#   alertmanager_url: http://localhost:9093

# frontend:
#   encoding: protobuf

# By default, Loki will send anonymous, but uniquely-identifiable usage and configuration
# analytics to Grafana Labs. These statistics are sent to https://stats.grafana.org/
#
# Statistics help us better understand how Loki is used, and they show us performance
# levels for most users. This helps us prioritize features and documentation.
# For more information on what's sent, look at
# https://github.com/grafana/loki/blob/main/pkg/analytics/stats.go
# Refer to the buildReport method to see what goes into a report.
#
# If you would like to disable reporting, uncomment the following lines:
#analytics:
#  reporting_enabled: false
