extensions:
  zpages:
    endpoint: otel-collector:55679
  health_check:
  # pprof:
  
  # file_storage/otc:
  #   directory: /var/lib/storage/otc
  #   timeout: 10s

receivers:
  filelog:
    include:
    - /var/lib/docker/containers/*/*-json.log
    operators:
    - id: container-parser
      type: container
      format: docker
      add_metadata_from_filepath: false
  # fluentforward:
  #   # endpoint: otel-collector:24224
  #   listenAddress: unix:///fluentd.sock

  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:
        endpoint: otel-collector:4318

  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      process:
      processes:
      paging:

  prometheus:
    config:
      global:
        scrape_interval: 15s
        scrape_timeout: 10s
      scrape_configs:
      - job_name: 'otel-collector'
        static_configs:
        - targets: ['otel-collector:8888']
      - job_name: 'loki'
        static_configs:
        - targets: ['loki:3100']
      - job_name: 'mimir'
        static_configs:
        - targets: ["mimir:8080"]
      # - job_name: "mimir-1"
      #   static_configs:
      #   - targets: ["mimir-1:8080"]
      # - job_name: "mimir-2"
      #   static_configs:
      #   - targets: ["mimir-2:8080"]
      # - job_name: "mimir-3"
      #   static_configs:
      #   - targets: ["mimir-3:8080"]


processors:
  batch:
    # send_batch_size: 1000
    # timeout: 10s

exporters:  
  debug:
    verbosity: detailed
    # sampling_initial: 5
    # sampling_thereafter: 200

  # File Exporter: ingest logs to local file
  # Ref: https://opentelemetry.io/docs/collector/deployment/agent/#example
  # file:
  #   path: ./app42_example.log
  #   rotation:

  otlphttp/logs:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
    # sending_queue:
    #   storage: file_storage/otc

  otlphttp:
    endpoint: http://mimir:8080/otlp
    tls:
      insecure: true
    # endpoint: http://mimir-1:8080/otlp
  
  prometheusremotewrite:
    endpoint: http://mimir:8080/api/v1/push
    # endpoint: http://mimir-1:8080/api/v1/push
    tls:
      insecure: true
    # headers:
    #   X-Scope-OrgID: demo


service:
  extensions: [zpages, health_check]
  # extensions: [zpages, health_check, file_storage]

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/logs]
    logs/filelog:
      receivers: [filelog]
      processors: [batch]
      exporters: [debug]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [otlphttp]
    # metrics/hostmetrics:
    #   receivers: [hostmetrics]
    #   exporters: [debug]

  telemetry:
    metrics:
      readers:
      - pull:
          exporter:
            prometheus:
              host: 'otel-collector'
              port: 8888
    logs:
      processors:
        - batch:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: http://otel-collector:4318
