extensions:
  zpages:
    endpoint: 0.0.0.0:55679
  health_check:
  # pprof:
  
  # file_storage/otc:
  #   directory: /var/lib/storage/otc
  #   timeout: 10s

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      process:
      processes:
      paging:

  prometheus:
    config:
      global:
        scrape_interval: 15s
        scrape_timeout: 10s
      scrape_configs:
      - job_name: "mimir-1"
        static_configs:
        - targets: ["mimir-1:8080"]
      - job_name: "mimir-2"
        static_configs:
        - targets: ["mimir-2:8080"]
      - job_name: "mimir-3"
        static_configs:
        - targets: ["mimir-3:8080"]
      - job_name: 'otel-collector'
        static_configs:
        - targets: ['0.0.0.0:8888']


processors:
  batch:
    # send_batch_size: 1000
    # timeout: 10s

exporters:  
  debug:
    verbosity: detailed
    # sampling_initial: 5
    # sampling_thereafter: 200

  # File Exporter: ingest logs to local file
  # Ref: https://opentelemetry.io/docs/collector/deployment/agent/#example
  # file:
  #   path: ./app42_example.log
  #   rotation:

  otlphttp/logs:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
    # sending_queue:
    #   storage: file_storage/otc

  otlphttp:
    endpoint: http://mimir-1:8080/otlp
  
  prometheusremotewrite:
    endpoint: http://mimir-1:8080/api/v1/push
    tls:
      insecure: true
    headers:
      X-Scope-OrgID: demo


service:
  extensions: [zpages, health_check]
  # extensions: [zpages, health_check, file_storage]

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/logs]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]
    # metrics/hostmetrics:
    #   receivers: [hostmetrics]
    #   exporters: [debug]

  telemetry:
    metrics:
      readers:
      - pull:
          exporter:
            prometheus:
              host: '0.0.0.0'
              port: 8888
    logs:
      processors:
        - batch:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: http://otel-collector:4318
