receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  prometheus:
    config:
      global:
        scrape_interval: 15s
        scrape_timeout: 10s
      scrape_configs:
      - job_name: "mimir-1"
        static_configs:
        - targets: ["mimir-1:8080"]
      - job_name: "mimir-2"
        static_configs:
        - targets: ["mimir-2:8080"]
      - job_name: "mimir-3"
        static_configs:
        - targets: ["mimir-3:8080"]
      - job_name: 'otel-collector'
        static_configs:
        - targets: ['0.0.0.0:8888']
      # - job_name: 'flask'
      #   static_configs:
      #     - targets: ['127.0.0.1:5000']


processors:
  batch:
    # send_batch_size: 1000
    # timeout: 10s

exporters:
  # logging:
  #   # verbosity: detailed
  #   logLevel: debug

  otlphttp/logs:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

  otlphttp:
    endpoint: http://mimir-1:8080/otlp
  
  prometheusremotewrite:
    endpoint: http://mimir-1:8080/api/v1/push
    tls:
      insecure: true
    headers:
      X-Scope-OrgID: demo


service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/logs]
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]
