apiVersion: 1

datasources:
- name: Loki
  uid: loki_uid
  type: loki
  access: proxy
  url: http://loki:3100
  isDefault: true
  editable: true
  # jsonData:
  #   maxLines: 1000
  #   derivedFields:
  #     # Field with internal link pointing to data source in Grafana.
  #     # datasourceUid value can be anything, but it should be unique across all defined data source uids.
  #     - datasourceUid: tempo_uid
  #       # "trace_id":\s*"([^"]+)"
  #       matcherRegex: "\"trace_id\":\\s*\"([^\"]+)\""
  #       name: trace_id
  #       # url will be interpreted as query for the datasource
  #       url: 'http://loki:3100/trace/$${__value.raw}'
  #       # optional for URL Label to set a custom display label for the link.
  #       urlDisplayLabel: 'View Trace'

- name: Tempo
  uid: tempo_uid
  type: tempo
  access: proxy
  url: http://tempo:3200
  isDefault: false
  editable: true
  jsonData:
    tracesToLogsV2:
      datasourceUid: loki_uid
      spanStartTimeShift: '-1h'
      spanEndTimeShift: '1h'
      # tags: [{ key: 'service.name', value: 'service_name' }]
      customQuery: true
      query: '{service_name=~".+"} | label_format level=detected_level | trace_id="$${__span.traceId}" | span_id="$${__span.spanId}"'
